version: '2'

services:
  php:
    container_name: yii2-php
    image: yiisoftware/yii2-php:8.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/app
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - db

  db:
    container_name: yii2-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_dataseed
      MYSQL_USER: dataseed
      MYSQL_PASSWORD: dataseed
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
